Repository BigOasis/Python, pull requests merged in 2025-08, with the labels that each got.

#1 [250816] BOJ 트리의 부모 찾기
  YoungjuLee/Week1/BOJ_11725_트리의_부모_찾기.py
  YoungjuLee/Week1/PGS_문제번호_문제명.py
Labels: BOJ

#8 [250819] PGS 후보키
  YoungjuLee/Week1/PGS_42890_후보키.py
Labels: Programmers

#9 [250819] PGS 후보키
  minji/Week1/PGS_42890_후보키.py
Labels: Programmers

#12 [250819] PGS 후보키
  JiaBae/Week1/PGS_42890_후보키.py
Labels: Programmers

#13 [250819] PGS 후보키
  HeeseungChoi/Week1/PGS_42890_후보키.py
Labels: Programmers

#18 [1주차] JiaBae - 12문제
  JiaBae/Week1/LTC_Binary_Search.py
  JiaBae/Week1/LTC_Combinations.py
  JiaBae/Week1/LTC_N_Queen.py
  JiaBae/Week1/LTC_Palindrome_Partitioning.py
  JiaBae/Week1/LTC_Permutation_Sequence.py
  JiaBae/Week1/LTC_Permutations.py
  JiaBae/Week1/LTC_Subsets.py
  JiaBae/Week1/LTC_Sudoku_Solver.py
  JiaBae/Week1/LTC_Two_Sum.py
  JiaBae/Week1/LTC_Word_Search.py
  JiaBae/Week1/PGS_42890_후보키.py
  JiaBae/Week1/PGS_72411_메뉴리뉴얼.py
  JiaBae/Week1/PGS_87946_피로도.py
Labels: Programmers, Leetcode

#20 [1주차] HeeSeungChoi- 6문제
  HeeseungChoi/Week1/LCT_Binary Search.py
  HeeseungChoi/Week1/LCT_Combinations.py
  HeeseungChoi/Week1/LCT_Permutations.py
  HeeseungChoi/Week1/LCT_Subsets.py
  HeeseungChoi/Week1/LCT_TwoSum.py
  HeeseungChoi/Week1/PGS_72411_메뉴 리뉴얼.py
Labels: Programmers, week, Leetcode

#15 [1주차] DaheeJeong - 9문제
  DaheeJeong/Week1/LTC_131_Palindrome_Partitioning.py
  DaheeJeong/Week1/LTC_1_Two_Sum.py
  DaheeJeong/Week1/LTC_46_Permutations.py
  DaheeJeong/Week1/LTC_704_Binary_Search.py
  DaheeJeong/Week1/LTC_77_Combinations.py
  DaheeJeong/Week1/LTC_78_Subsets.py
  DaheeJeong/Week1/LTC_79_Word_Search.py
  DaheeJeong/Week1/PGS_42890_후보키.py
  DaheeJeong/Week1/PGS_72411_메뉴_리뉴얼.py
  DaheeJeong/Week1/PGS_87946_피로도.py
Labels: Programmers, Leetcode
